Laravel core changes
ladybirdweb/agora-invoicing-community pull request #1196
Opened 2020-07-01 17:33 UTC by ashu555

Fixes #1195 
Moved all the changes directly into laravel core files into project's core file

2020-08-19 13:18 UTC, SarfrazS requested changes
Testing done all pages checked whether open or not and functionality.
https://docs.google.com/document/d/1sWnxLbXhd6SMGXU7ss9T1nWlyKr8PP5gs4Gdn3Z3jDg/edit
Please fix and let us know

2020-08-26 12:14 UTC, SarfrazS approved these changes
I checked all curd and functionality working, some issues are created separately.
I am approving this PR but some issues are fixed on another PR  Taxes PR.

2020-08-28 05:24 UTC, mverma16 approved these changes

2020-08-28 05:24 UTC, mverma16 commented on app/Http/Controllers/Front/CheckoutController.php
> +            dd($ex);
remove live dd

2020-08-28 21:00 UTC, closed without merging