Creating Freetrial option for newly registered users
ladybirdweb/agora-invoicing-community pull request #1709
Opened 2022-03-07 09:47 UTC by sowmiyasubramaniyan

This PR is about creating a free trial option for newly registered users
        1. Here I have created the Faveo cloud trial button.
        2. When a new user clicks that button it will create the invoice and order for the Trail product.
        3. And it will call the tenant API and create the domain for users.

2022-03-07 15:14 UTC, sandesh556 requested changes

2022-03-07 15:14 UTC, sandesh556 commented on vendor/doctrine/deprecations/test_fixtures/vendor/doctrine/foo/Bar.php
> +<?php
Remove this files from the PR

2022-03-07 15:14 UTC, sandesh556 commented on vendor/doctrine/deprecations/test_fixtures/vendor/doctrine/foo/Baz.php
> +<?php
Remove this file from this PR

2022-03-08 08:31 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +        $this->invoice = $invoice;
Avoiding unnecessary variable declaration. You can write $this->invoice = new Invoice();

2022-03-08 08:32 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +        $this->order = $order;
As above mentioned

2022-03-08 08:34 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +        $this->subscription = $subscription;
remove variable

2022-03-08 08:37 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +            $invoice = $this->generateFreetrailInvoice();
Please remove unused variable declaration $invoice,$user,$inoice_items

2022-03-08 08:42 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +            return successResponse(Lang::get('message.succs_fre'), $order, 200);
refactor the code
return successResponse(trans('message.succs_fre'), $this->executeFreetrailOrder(), 200);

2022-03-08 08:48 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +            $grand_total = round($grand_total);
make it ternary operator for $grand_total

2022-03-08 08:50 UTC, RafficMohammed commented on app/Http/Controllers/FreeTrailController.php
> +        $product = Product::where('name', $item->product_name)->first()->id;
value('id')

2022-04-07 07:42 UTC, sandesh556 requested changes

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +        $invoice = DB::table('invoices')->where('user_id', $userId)->first();
use the model

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +        $invoice_items = DB::table('invoice_items')->where('invoice_id', $invoiceid)->get();
same

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +                    break;
Don't have to use break for default case

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/Order/BaseOrderController.php
> +            $user_id = DB::table('orders')->find($orderid)->client;
use the model

2022-04-07 07:42 UTC, sandesh556 commented on resources/views/themes/default1/layouts/front/master.blade.php
> +                                                    $user = DB::table('users')->where('id', '=', $id)->value('first_time_login');?>
use model

2022-04-07 07:42 UTC, sandesh556 commented on routes/web.php
> +            Route::post('firstlogin', 'FreeTrailController@firstloginatem');
use - to maintain uniformity

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +<?php
Also, use code comments I see no comments in most methods

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +    public function firstloginatem(Request $request)
function names should be camelCase

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +        $invoice = DB::table('invoices')->where('user_id', $userId)->first();
use model

2022-04-07 07:42 UTC, sandesh556 commented on app/Http/Controllers/FreeTrailController.php
> +        $plan_id = Plan::where('product', '=', $product)
No need to use = in where clause

2022-04-07 07:42 UTC, sandesh556 commented on tests/Unit/FreeTrialControllerTest.php
> +        $product = factory(Product::class)->create();
no need of unnecessary variables

2022-04-07 07:43 UTC, sandesh556 commented
Also fix the codacy issues @sowmiyasubramaniyan

2022-04-07 07:44 UTC, closed without merging