Bug fixes for billing
ladybirdweb/agora-invoicing-community pull request #1711
Opened 2022-03-07 10:19 UTC by sowmiyasubramaniyan

Issue fix : #866 ,#1542, 1048

2022-03-07 14:21 UTC, sandesh556 requested changes
Also check if those image files that are present in the PR are present in development or master. If not remove them also

2022-03-07 14:21 UTC, sandesh556 commented on app/Exceptions/Handler.php
> +        // dd($exception);
Remove this comment and dd($exception) from the PR

2022-03-07 14:21 UTC, sandesh556 commented on storage/installed
> +Agora Invoicing Installer successfully INSTALLED on 2022/01/11 07:39:16am
Remove this also from the PR

2022-03-07 14:31 UTC, sandesh556 requested changes

2022-03-07 14:31 UTC, sandesh556 commented on app/Http/Controllers/Common/SettingsController.php
> +    public function changeLogo($id, $value)
Add code comments to this fucntion

2022-04-25 04:47 UTC, sandesh556 requested changes

2022-04-25 04:47 UTC, sandesh556 commented on app/Http/Controllers/Common/SettingsController.php
> +        $result = DB::table('settings')->where('id', $id)->update([$value => null]);
use models instead of query builders

2022-05-02 08:23 UTC, sandesh556 approved these changes

2022-05-11 11:31 UTC, SarfrazS requested changes
Last commit:-
![image](https://user-images.githubusercontent.com/18435376/167834114-3ca009e4-60ef-43f2-a210-cafb3210e6cb.png)
Not working.
#866:- Not working.
![image](https://user-images.githubusercontent.com/18435376/167839211-eb686960-2b45-41f4-b360-acfc0f05aff3.png)

#1542:- Not working.
![image](https://user-images.githubusercontent.com/18435376/167839083-bd19bb81-f1f5-44b3-9bea-09d624d4acf9.png)

#1048:- Not working.
![b2](https://user-images.githubusercontent.com/18435376/167838489-1fec9da6-6b5d-48d9-91af-aacc5e66aaee.png)

2022-06-16 04:05 UTC, sandesh556 approved these changes

2022-07-13 10:52 UTC, priyadarshini2101 requested changes
Tested the pr with existing db on server.

- [ ] Issue 1:Unable to delete the logo once uploaded in the system settings.

Before fix
![jul13logo before fix](https://user-images.githubusercontent.com/91872895/178711578-ce688a2e-5d81-47ca-add0-21cd5fd0c6ec.jpg)

After fix
![jul13logo after fix](https://user-images.githubusercontent.com/91872895/178711572-c042510c-256e-459b-bdfd-3e4fc9b21927.jpg)

Other Issues pointed are fixed.

Redirection Issue

Before fix

![jul13redirect before fix](https://user-images.githubusercontent.com/91872895/178711963-80adadf7-222c-4712-ad0c-cc1ebbcbd609.jpg)

After fix

![jul13redirect after fix](https://user-images.githubusercontent.com/91872895/178711960-e9d9bc3c-d2ca-447c-b954-b47394e39240.jpg)


System Email should be unique

Before fix

![jul13mail before fix](https://user-images.githubusercontent.com/91872895/178716591-5ea03081-397d-498b-971d-2ec0f421dadb.jpg)

After fix

![jul13mail after fix](https://user-images.githubusercontent.com/91872895/178716586-8b86a0e4-935e-4934-8b6c-a67ae38f7183.jpg)

2022-07-14 08:56 UTC, RafficMohammed approved these changes

2022-07-19 13:33 UTC, sowmiyasubramaniyan commented
**Issue 1:Unable to delete the logo once uploaded in the system settings**
  Fixed

2022-07-20 12:03 UTC, priyadarshini2101 requested changes
Tested the pr with existing db on server.

Issue 1:When the file uploaded is of type txt or someother unsupported format for either of one Admin Panel logo/Favicon/Client Panel logo . The alert message is displaying. But,the files uploaded to these are all getting vanished. —--Is it fine?

Issue 2:When the logo is deleted for either of one Admin Panel logo/Favicon/Client Panel logo, the API is not showing.

jul20logo

![jul20logo](https://user-images.githubusercontent.com/91872895/179977223-7926952e-cd23-4dce-9fd0-d53158367d5a.jpg)


Issue 3:When same logo is uploaded for Admin Panel logo/Favicon/Client Panel logo, and try to delete the logo of Admin Panel, the same logo uploaded in other places the images are breaking.

Note 1:Popup alert message for Deletion of logo is not user friendly.
Note 2:Alert messages are not vanishing after displaying staying for a long.

2022-07-20 12:53 UTC, priyadarshini2101 approved these changes
Created seperate issue and approving this pr.

https://github.com/ladybirdweb/agora-invoicing-community/issues/1875

2022-07-21 12:30 UTC, Sheetal34 approved these changes
Tested for mentioned fixes. Working fine

2022-07-21 12:53 UTC, merged