Bugfix billing
ladybirdweb/agora-invoicing-community pull request #1742
Opened 2022-04-27 10:26 UTC by sowmiyasubramaniyan

Issue fix in Auto PHP Licenser

2022-04-28 06:53 UTC, sandesh556 requested changes

2022-04-28 06:53 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +        $api_key_secret = $this->api_key_secret;
if you're not using API key remove this

2022-04-28 06:53 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +        $getkey = $this->getCurl($url.'api/admin/viewApiKeys?token='.$token);
you can use $this->token directly, only create a variable if it's used in multiple places

2022-05-02 08:16 UTC, sandesh556 approved these changes

2022-05-02 08:45 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +    private function getCurl($get_url)
add comments to this function

2022-05-02 08:45 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +    public function getLicensekey()
add comments to this function

2022-05-12 07:43 UTC, SarfrazS requested changes
Issue 1:- After saving also, valid alert message not vanishing.
![image](https://user-images.githubusercontent.com/18435376/168017152-afc460de-15a2-4033-8433-eadd54734dec.png)

Issue 2:- If we entered api secret and api url both invaild then in api url field alert message not showing.
![image](https://user-images.githubusercontent.com/18435376/168017500-13156b6b-e47f-4f3b-91dc-9cafa08844dd.png)
Issue 3:- first time we entered invalid values and click on save getting alert message after that entering valid values still showing alert message.(api secret is valid)
![image](https://user-images.githubusercontent.com/18435376/168018293-ce67d0cb-a07e-42f1-9182-ef9b8e1278ad.png)

2022-05-16 06:13 UTC, SarfrazS approved these changes
Working fine.

2022-05-16 10:38 UTC, bindu95 approved these changes
**BEFORE FIX**
Entering invalid license key and saving, showing success message
<img width="1440" alt="Screenshot 2022-05-16 at 4 05 20 PM" src="https://user-images.githubusercontent.com/27956111/168574970-b6168430-79ea-4ed0-b447-1c258a5d0cb0.png">


**AFTER FIX**
Showing alert when we are saving with incorrect license key
<img width="1440" alt="Screenshot 2022-05-16 at 4 07 38 PM" src="https://user-images.githubusercontent.com/27956111/168575288-c1a4f0fb-223e-415f-b5b6-ff822c8f5fe3.png">

2022-05-16 11:22 UTC, sandesh556 approved these changes

2022-06-24 04:41 UTC, RafficMohammed approved these changes

2022-07-07 09:55 UTC, merged