Order issue
ladybirdweb/agora-invoicing-community pull request #1752
Opened 2022-05-04 08:11 UTC by sowmiyasubramaniyan

Issue fix: #1533

2022-05-12 08:01 UTC, SarfrazS requested changes
Not fixed
![image](https://user-images.githubusercontent.com/18435376/168021060-bbce6b68-4bd8-4848-a30c-0c36dc4cb14c.png)
Now click on view and then click on customer details
![image](https://user-images.githubusercontent.com/18435376/168021704-8e9e3008-46d2-4622-bef3-4d23a4fd8dea.png)

2022-05-12 09:30 UTC, SarfrazS approved these changes
Working fine.
![image](https://user-images.githubusercontent.com/18435376/168039327-a79346cf-092c-4cd5-a29b-eedf133de58e.png)

2022-05-12 09:36 UTC, sandesh556 approved these changes

2022-05-16 08:06 UTC, bindu95 approved these changes
**BEFORE FIX**
When we are filtering from May 10th 2021 to Nov 4th 2021, the results of may10th and nov4th are not showing.Total results as 180
<img width="1235" alt="Screenshot 2022-05-16 at 1 31 28 PM" src="https://user-images.githubusercontent.com/27956111/168546724-3cd115e8-7b74-4a67-92cd-412e30e1c858.png">
<img width="1235" alt="Screenshot 2022-05-16 at 1 31 44 PM" src="https://user-images.githubusercontent.com/27956111/168546701-232df115-7843-48f1-809f-c8e62473e101.png">


**LAST COMMIT**
<img width="717" alt="Screenshot 2022-05-16 at 1 34 02 PM" src="https://user-images.githubusercontent.com/27956111/168547132-5f31059e-aa38-41b2-9750-821f1901e399.png">


**AFTER FIX**
<img width="1235" alt="Screenshot 2022-05-16 at 1 31 28 PM" src="https://user-images.githubusercontent.com/27956111/168546724-3cd115e8-7b74-4a67-92cd-412e30e1c858.png">
<img width="1232" alt="Screenshot 2022-05-16 at 1 35 26 PM" src="https://user-images.githubusercontent.com/27956111/168547259-f395cabb-0cd5-4ce3-953a-971835b171f9.png">

2022-06-24 04:37 UTC, RafficMohammed approved these changes

2022-07-07 08:00 UTC, merged