Issue 1567
ladybirdweb/agora-invoicing-community pull request #1759
Opened 2022-05-06 10:45 UTC by sowmiyasubramaniyan

Issue fix: #1567

2022-05-12 08:06 UTC, SarfrazS requested changes
Not fixed
Last commit:-
![image](https://user-images.githubusercontent.com/18435376/168022594-d42bc1a2-9e1f-418c-a2f3-40c0a95eac87.png)

![image](https://user-images.githubusercontent.com/18435376/168021060-bbce6b68-4bd8-4848-a30c-0c36dc4cb14c.png)
Now click on view and then click on customer details
![image](https://user-images.githubusercontent.com/18435376/168021704-8e9e3008-46d2-4622-bef3-4d23a4fd8dea.png)

2022-05-13 04:19 UTC, sandesh556 requested changes

2022-05-13 04:19 UTC, sandesh556 commented on app/Http/Controllers/User/ClientController.php
> +            $managers = User::select(DB::raw('CONCAT(first_name, " ", last_name) As first_name'), 'id')
Need to think of a better way than using raw queries

2022-05-16 03:57 UTC, sandesh556 approved these changes

2022-05-16 09:25 UTC, SarfrazS approved these changes
![image](https://user-images.githubusercontent.com/18435376/168561687-6b941066-e930-48d0-b09f-e71222e83149.png)
![image](https://user-images.githubusercontent.com/18435376/168561818-4f10e2bf-b36d-4a03-a7d5-119d34fe5a84.png)

2022-05-16 10:48 UTC, bindu95 approved these changes
**BEFORE FIX**
_EDIT USER:_
<img width="1440" alt="Screenshot 2022-05-16 at 4 15 54 PM" src="https://user-images.githubusercontent.com/27956111/168576660-31a82636-d0ab-448c-ae07-5935c64e7d85.png">

_VIEW USER:_
<img width="1440" alt="Screenshot 2022-05-16 at 4 16 14 PM" src="https://user-images.githubusercontent.com/27956111/168576678-58ce82bb-44f0-46b9-9923-f60d3ffa5d55.png">


**AFTER FIX**
_EDIT USER:_
<img width="1440" alt="Screenshot 2022-05-16 at 4 17 49 PM" src="https://user-images.githubusercontent.com/27956111/168576778-ab2475a2-d55f-4178-81df-cea62e608185.png">

_VIEW USER:_
<img width="1440" alt="Screenshot 2022-05-16 at 4 16 14 PM" src="https://user-images.githubusercontent.com/27956111/168576678-58ce82bb-44f0-46b9-9923-f60d3ffa5d55.png">

2022-06-20 16:53 UTC, RafficMohammed approved these changes

2022-07-07 07:57 UTC, merged