issue fixed in Invoice page
ladybirdweb/agora-invoicing-community pull request #1833
Opened 2022-06-29 09:33 UTC by sowmiyasubramaniyan

Bugfix: #1536

2022-06-30 06:45 UTC, RafficMohammed commented on app/Http/Controllers/Order/InvoiceController.php
>          ], [
If you have more number of rules, better create in Request file Which will look good clean code and better approach

2022-07-12 06:25 UTC, sandesh556 approved these changes

2022-07-13 09:07 UTC, priyadarshini2101 requested changes
Tested the pr with existing db on server.

- [ ] Issue 1:In master after generating invoice.

![jul13in master](https://user-images.githubusercontent.com/91872895/178695277-7021937f-6e3f-4ed4-9798-9f9c692eaaaf.jpg)

In this branch

![jul13invoice after fix](https://user-images.githubusercontent.com/91872895/178695689-dfa9a795-b1d4-42b8-b63a-6f01448c4aa8.jpg)



Pointed issues are fixed.
Before fix

![jul13 field exist](https://user-images.githubusercontent.com/91872895/178685911-eb1b07a6-b491-4bd3-ba4b-ff4ad471c020.jpg)


After fix

![jul13 field after fix](https://user-images.githubusercontent.com/91872895/178685894-c4649dc6-ec7d-463e-b1c4-7f72045f96b7.jpg)


Before fix

![jul13invoice exist](https://user-images.githubusercontent.com/91872895/178686127-0a610d8f-5f2a-464b-a94f-fb2b745ab138.jpg)


After fix

![jul13invoice after fix](https://user-images.githubusercontent.com/91872895/178686116-dac1fcbd-c981-4592-b2c5-1de9112140b5.jpg)

Note: Checked only the pointed issues.

2022-07-15 12:26 UTC, Sheetal34 approved these changes
**Tested with existing db locally**
Mentioned issues are fixed

Before fix:
Invoice values not vanished after saving invoice
![image](https://user-images.githubusercontent.com/92353368/179213386-a7bdbd60-d9ff-4a69-87ac-66656fdde3fa.png)

After fix:
Invoice values vanished after saving invoice
![image](https://user-images.githubusercontent.com/92353368/179213696-d419ca42-3da3-4877-bf0a-4e6677371024.png)
![image](https://user-images.githubusercontent.com/92353368/179213739-55dcafaa-0c64-4d71-91e3-dbf441879ba9.png)

2022-07-16 08:03 UTC, merged