Installer - Application name
ladybirdweb/agora-invoicing-community pull request #1836
Opened 2022-06-29 10:19 UTC by sowmiyasubramaniyan

Bugfix: #1353

2022-06-30 06:40 UTC, RafficMohammed approved these changes

2022-07-08 02:41 UTC, sandesh556 approved these changes

2022-07-08 06:27 UTC, priyadarshini2101 requested changes
After removing the app name textfield from agora installation, still the App name is showing with empty value in the database.

2022-07-21 06:42 UTC, Sheetal34 approved these changes
Tested for mentioned fixes. Working fine.

2022-07-21 12:54 UTC, merged