Order filter - Expiring subscription search
ladybirdweb/agora-invoicing-community pull request #1912
Opened 2022-09-29 06:15 UTC by sowmiyasubramaniyan

Option to see the Orders which are expiring on Future Days/Dates

2022-09-29 12:16 UTC, RafficMohammed commented on app/Http/Controllers/Order/OrderSearchController.php
> +            if ($request->renewal == 'expiring_subscription') {
use ternary operator

2022-09-29 12:17 UTC, RafficMohammed commented on app/Http/Controllers/Order/OrderSearchController.php
> +        if ($request->renewal = 'expiring_subscription') {
use ternary

2022-09-29 12:17 UTC, RafficMohammed commented on app/Http/Controllers/Order/OrderSearchController.php
> +            $subTo = 'subscriptions.update_ends_at';
here too

2022-10-04 12:42 UTC, RafficMohammed approved these changes

2022-12-05 03:33 UTC, bhanu2217 commented
Is this P.R for this issue? https://github.com/ladybirdweb/agora-invoicing-community/issues/1930

2022-12-22 04:47 UTC, sandesh556 approved these changes

2022-12-22 04:48 UTC, sandesh556 commented
@sowmiyasubramaniyan rebase this

2022-12-22 09:11 UTC, sandesh556 approved these changes

2023-01-03 04:46 UTC, RafficMohammed commented on app/Http/Controllers/Order/OrderSearchController.php
> +            return $request->renewal == 'expiring_subscription' ? $baseQuery->orderBy('subscriptions.update_ends_at', 'asc') :
check this

2023-01-03 04:47 UTC, RafficMohammed requested changes
Check ternary operator

2023-01-05 09:14 UTC, sandesh556 submitted a review, later dismissed

2023-02-07 09:47 UTC, priyadarshini2101 submitted a review, later dismissed
Option to see the Orders which are expiring on Future Days/Dates
After fix

![feb7af1](https://user-images.githubusercontent.com/91872895/217209912-bac95be3-41da-4f67-ae58-b3dfc36d2cc1.jpg)

2023-02-09 06:24 UTC, SarfrazS submitted a review, later dismissed
Working fine.

2023-02-13 04:26 UTC, sandesh556 commented
Rebase this PR properly

2023-02-14 11:00 UTC, closed without merging