Bugfixes in client panel
ladybirdweb/agora-invoicing-community pull request #1986
Opened 2022-12-21 12:38 UTC by sowmiyasubramaniyan

2022-12-21 12:39 UTC, RafficMohammed commented on app/Http/Controllers/Common/MailChimpController.php
> +                return errorResponse('Member already exists!', 400);
use lang

2022-12-21 12:40 UTC, RafficMohammed commented on app/Http/Controllers/Front/PageController.php
> +            'name' => 'required|unique:frontend_pages,name',
use validation file for this

2022-12-21 12:42 UTC, RafficMohammed requested changes
use trans everywhere and test cases too

2022-12-26 04:25 UTC, sandesh556 requested changes

2022-12-26 04:25 UTC, sandesh556 commented on app/Http/Controllers/Front/PageController.php
> +            if ($pages_count <= 2) {
You don't need to use if else for return conditions

2022-12-26 04:25 UTC, sandesh556 commented on public/js/intl/js/utils.js
>  "$1 $2 $3",["2[14-68]|3[26-9]|4[1246-8]|6(?:1|75)|7[1-35]|8[1-36]"],"(0$1)"],[,"(\\d{2})(\\d{3})(\\d{4})","$1 $2 $3",["87"]],[,"(\\d{3})(\\d{6})","$1 $2",["9(?:[5-79]|8[1-6])"],"0$1"],[,"(\\d{3})(\\d
why is this here?

2022-12-27 04:48 UTC, sowmiyasubramaniyan commented on public/js/intl/js/utils.js
>  "$1 $2 $3",["2[14-68]|3[26-9]|4[1246-8]|6(?:1|75)|7[1-35]|8[1-36]"],"(0$1)"],[,"(\\d{2})(\\d{3})(\\d{4})","$1 $2 $3",["87"]],[,"(\\d{3})(\\d{6})","$1 $2",["9(?:[5-79]|8[1-6])"],"0$1"],[,"(\\d{3})(\\d
I have made a change in this file

2022-12-27 09:38 UTC, sandesh556 submitted a review, later dismissed

2023-01-03 04:41 UTC, RafficMohammed requested changes
Write test cases for the request validation field too.

2023-01-12 05:31 UTC, sandesh556 approved these changes

2023-02-09 06:04 UTC, SarfrazS requested changes
Below Issues are not fixed Please fix and update me.
 - [ ] Mismatch in displaying the alert message and field name showing on the page.
- [ ] The calendar option is not proper, Not able to select the particular year in the calendar on the Edit page.
- [ ] 2FA Alert message is showing wrong when we are passing invalid.

2023-02-13 10:06 UTC, SarfrazS requested changes
Increase the number of values in name. as of not taking only 10.
![image](https://user-images.githubusercontent.com/18435376/218427980-31386741-fd35-4015-8b25-860fc3d19cce.png)
Edit/Update Publishing Date not showing correct. i updated from 13/02/2023 to  14/92/2023 but showing as below.
![image](https://user-images.githubusercontent.com/18435376/218428222-66f89dea-8e43-4cd9-bf5c-234a6c158d30.png)

2023-02-14 13:21 UTC, SarfrazS approved these changes
Pointed issue fixed now
![image](https://user-images.githubusercontent.com/18435376/218750692-d958afe7-23b7-4a11-b6dc-f7f6beff45d8.png)

2023-02-14 13:22 UTC, merged