Bugfixes in Invoice Module
ladybirdweb/agora-invoicing-community pull request #2004
Opened 2022-12-28 12:41 UTC by sowmiyasubramaniyan

2023-01-09 09:53 UTC, ajaz-ul-haq commented on app/Http/Controllers/Order/InvoiceController.php
> +                       })
need to refactor whole block of code, 

Can't we use some thing like  below : 
                     ->filterColumn('status', function ($query, $keyword) {
                           $query->where('status','LIKE', '%'.$this->fetchKeyWordForQuery($keyword).'%' );
                       })
and 
    private function fetchKeyWordForQuery($keyword = 'Paid'): string
    {
        return match ($keyword){
            'Paid' => 'success',
            'Unpaid' => 'pending',
            'Partiallypaid' || 'Partially' => 'partially paid'
        };
    }

2023-01-10 10:57 UTC, ajaz-ul-haq commented on app/Http/Controllers/Order/InvoiceController.php
> +
please give proper indentation

2023-01-10 12:26 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Order/InvoiceController.php
> +
Done

2023-01-12 06:06 UTC, ajaz-ul-haq approved these changes

2023-02-07 06:36 UTC, priyadarshini2101 requested changes
- [ ] The search textbox is not working with the status Keyword “paid”.---- fixed but, not searching for the other words and there are UI changes in pdf alignment. Shown to sowmya. Once fixed will retest the pr.

2023-02-07 10:40 UTC, priyadarshini2101 submitted a review, later dismissed
Tested the pr with server instance.

- [ ]  CIN, GSTIN, and Phone no. values are overlapping while generating pdf.

- [ ] Generate pdf alignment is not aligned properly.

![feb7af2](https://user-images.githubusercontent.com/91872895/217222299-da47ea3d-4f75-4403-a2ad-9b4e0cd5b317.jpg)

- [ ] The search textbox is not working with the status Keyword “paid”.

![feb7pd](https://user-images.githubusercontent.com/91872895/217222492-fc268c3f-24bb-4aa5-95a3-ce98c302bd69.jpg)

2023-02-08 13:28 UTC, SarfrazS requested changes
- [ ]  The search textbox is not working with the status Keyword “paid”.  Not working in client panel.
![image](https://user-images.githubusercontent.com/18435376/217543356-49d7f589-e387-4e91-a657-94ca7ae85bc1.png)

2023-02-13 08:04 UTC, SarfrazS submitted a review, later dismissed
Pointed issue fixed.
![image](https://user-images.githubusercontent.com/18435376/218402977-c252a96b-6dc1-4243-829a-18f45c47d56e.png)

2023-02-14 10:39 UTC, merged