Email link issue fix
ladybirdweb/agora-invoicing-community pull request #2041
Opened 2023-01-11 12:07 UTC by sowmiyasubramaniyan

Fix: #1953 & #1866

2023-01-11 13:00 UTC, ajaz-ul-haq approved these changes

2023-01-13 14:13 UTC, saddamhmalik01 approved these changes

2023-01-18 05:41 UTC, Sheetal34 requested changes
**Tested with existing db on server:**
Facing issue there:

- [ ] **When new user is registered from admin panel - Create user by setting Inactive to Email and Mobile we send a verification mail to user.
And there is a link provided to set a password which is not working**
After fix:
Now that passowrd link not clickable 
![image](https://user-images.githubusercontent.com/92353368/213093261-c399eefb-ec3c-40cb-850d-d13460e29d91.png)

2023-01-19 05:38 UTC, sowmiyasubramaniyan commented
> **Tested with existing db on server:** Facing issue there:
> 
> * [ ]  **When new user is registered from admin panel - Create user by setting Inactive to Email and Mobile we send a verification mail to user.
>   And there is a link provided to set a password which is not working**
>   After fix:
>   Now that passowrd link not clickable
>   ![image](https://user-images.githubusercontent.com/92353368/213093261-c399eefb-ec3c-40cb-850d-d13460e29d91.png)

Fixed

2023-01-20 08:53 UTC, closed without merging