Issues related to uploading of logo from the system settings
ladybirdweb/agora-invoicing-community pull request #2155
Opened 2023-03-27 09:49 UTC by sowmiyasubramaniyan

2023-03-29 05:00 UTC, sandesh556 requested changes
remove unwanted changes first and refactor

2023-04-19 04:15 UTC, sandesh556 requested changes

2023-04-19 04:15 UTC, sandesh556 commented on resources/views/themes/default1/common/setting/system.blade.php
> +           if (confirm("Are you sure you want to suspend this user?"))
Also where ever there are messages like this, when you work on it can you move it to the lang file

2023-04-24 06:34 UTC, sandesh556 submitted a review, later dismissed

2023-05-10 13:51 UTC, Sheetal34 commented
Facing an issue while checking out to pr branch. Not able to checkout

2023-05-10 14:12 UTC, ajaz-ul-haq submitted a review, later dismissed

2023-05-12 13:36 UTC, Sheetal34 requested changes
**Tested with existing db on server:**
Found issues:

- [ ] Upload file of type txt or some other unsupported format for Admin Panel logo/Favicon/Client Panel logo. Now click on upload. We will get an alert message for unsupported format. Check the last alert. Better to display The client panel logo instead of the logo.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/0ea77690-b29b-43b5-983a-bbe72e8c0fd6)

- [ ] Issue still there
Admin Panel > System settings
Select the admin panel logo and update. Admin panel logo showing on the dashboard.
Now click on the delete icon and delete the admin panel logo. Without clicking on update, the admin panel logo will be removed from the dashboard.

- [ ] For the Admin Panel logo, Favicon, and Client Panel logo also files are uploaded, but still, it's showing No file chosen. Happening in overall billing.
Note:- Need to confirm this issue. Once confirmed will create a separate issue for this one.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/6d8c1004-6873-438b-9fd3-08ed85f14c2b)

2023-05-13 09:54 UTC, Sheetal34 reviewed
**Tested with existing db on server:**
Both issues are fixed.

1. Upload a file of type txt or some other unsupported format for the Admin Panel logo/Favicon/Client Panel logo. Now click on upload. We will get an alert message for unsupported format. Check the last alert. Better to display The client panel logo instead of the logo.
**Before fix:**
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/1ebd766f-0c9d-4b6b-993a-5cd8a526d2fa)
**After fix:**
![Screenshot (2316)](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/8ab18462-e88e-4fc9-901a-bebd0a35b9f6)

2. For the Admin Panel logo, Favicon, and Client Panel logo also files are uploaded, but still, it's showing No file chosen.
**Before fix:**
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/926ded00-48e1-4e6d-b662-b56ba4cef3be)
**After fix:**
![Screenshot (2315)](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/fe4d1664-74d2-4527-9d83-f33b4394c859)

**Query:-** 

- Files are uploaded for the Admin panel logo, the client panel logo, and, the favicon, but still for all showing Upload Application logo, Upload favicon for admin and client panel, Upload the company logo. ----------- Is it fine?
![Screenshot (2315)](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/2576af0b-dcf3-4a37-a7dd-ed0bfd36bde4)

2023-05-15 12:04 UTC, Sheetal34 submitted a review, later dismissed
Cleared with queries. So, I'm approving the pr.

2023-05-27 08:16 UTC, SarfrazS approved these changes
working fine.

2023-05-31 05:57 UTC, merged