Cloud Free Trial Button Enable/Disable Option
ladybirdweb/agora-invoicing-community pull request #2221
Opened 2023-05-09 13:23 UTC by sowmiyasubramaniyan

2023-05-10 13:56 UTC, ajaz-ul-haq approved these changes

2023-05-17 04:46 UTC, laksh-22 commented on app/Http/Controllers/Tenancy/TenantController.php
> +        $cloudButton = StatusSetting::where('id', '1')->value('cloud_button');
you can directly use StatusSetting::value('cloud_button');

2023-05-17 04:46 UTC, laksh-22 commented on app/Http/Controllers/Tenancy/TenantController.php
> +            $debug == 'true' ? StatusSetting::where('id', '1')->update(['cloud_button' => '1']) : StatusSetting::where('id', '1')->update(['cloud_button' => '0']);
you can directly use $request->input('debug'); instead of creating a variable

2023-05-17 04:47 UTC, laksh-22 commented on app/Http/Controllers/Tenancy/TenantController.php
> +            $debug == 'true' ? StatusSetting::where('id', '1')->update(['cloud_button' => '1']) : StatusSetting::where('id', '1')->update(['cloud_button' => '0']);
and StatusSetting::first()->update(['cloud_button' => '1']) might also work

2023-05-17 05:38 UTC, laksh-22 submitted a review, later dismissed

2023-05-17 05:43 UTC, ajaz-ul-haq commented on app/Http/Controllers/Tenancy/TenantController.php
> +
**StatusSetting::first()->update(['cloud_button' => (int) $request->input('debug')]);**

Above can be replaced with this, i think Can you check please

2023-05-17 06:54 UTC, ajaz-ul-haq submitted a review, later dismissed

2023-05-31 16:39 UTC, SarfrazS requested changes
Last commit
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/c2e7e4cf-8729-4a7b-9f63-31ac7319ada2)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/053e944b-c4c7-49ce-a647-fb476c7952b5)
**Unable to test getting below error**
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/ecccf779-67bd-4650-90e9-3c874de001c5)

2023-06-09 04:07 UTC, SarfrazS commented
Please make it first later capital.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/1cede75a-584d-4a39-9d0c-2914d95acdbe)

2023-06-09 04:18 UTC, SarfrazS requested changes
Please don't miss basic things.

2023-06-09 05:44 UTC, SarfrazS submitted a review, later dismissed
Pointed issues were fixed.
**When setting is enabled then faveo Cloud button is showing on the client panel. (for logged-in users)**
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/9433159a-bfbb-4d9b-a8d3-ae2e346dba6c)
When the setting is Disabled then faveo Cloud button is not showing on the client panel. (for logged-in users)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5dcb5ca8-764b-41e1-a6de-713dc0dc4449)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/a4be51f7-37ca-4896-af5a-61eec2d05536)

Query:- Cloud Trail option is enabled and the user logged in user can see faveo cloud after that admin is set as Disabled, once the user refreshes the URL then only it is vanishing. Is it fine?

Note:- if Cloud trail set as disabled then i need to check cloud order is showing or not on the final build with live cloud data. here i am not able to test it.

2023-06-13 07:43 UTC, merged