Product renewal url
ladybirdweb/agora-invoicing-community pull request #2240
Opened 2023-05-22 10:28 UTC by sowmiyasubramaniyan

2023-05-23 06:36 UTC, ajaz-ul-haq commented on app/Http/Controllers/HomeController.php
> +         }
Use models instead of DB statement and acoid unneceesary variables

2023-05-23 10:47 UTC, ajaz-ul-haq submitted a review, later dismissed

2023-05-25 12:21 UTC, RafficMohammed commented on app/Http/Controllers/HomeController.php
> +             'domain' => 'required|no_http',
Create Request file

2023-05-25 12:27 UTC, RafficMohammed commented on tests/Unit/HomeControllerTest.php
> +        $request = new Request(['domain' => 'example.com']);
remove unwanted code

2023-05-25 12:53 UTC, RafficMohammed requested changes
Fix that issue

2023-05-26 04:54 UTC, RafficMohammed approved these changes

2023-05-29 11:50 UTC, SarfrazS submitted a review, later dismissed
Renewal API:- https://qa.productdemourl.com/saifbilling/public/renewurl?domain=sarfu.localhost/saiffaveo/public
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/8740a8fe-3a15-4edd-ab6f-010d715753d2)

Copy URL from response and paste on browser.
https://qa.productdemourl.com/saifbilling/public/autopaynow/13001
It is logged in then redirect to paynow page other with login then paynow page
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/ca97ad39-32a0-44d9-af24-71a1c85d8534)

2023-05-31 05:59 UTC, merged