Cloud Auto Deletion
ladybirdweb/agora-invoicing-community pull request #2282
Opened 2023-06-06 07:17 UTC by sowmiyasubramaniyan

2023-06-26 10:18 UTC, RafficMohammed commented on app/Http/Controllers/Common/BaseSettingsController.php
> +        $allStatus->cloud_mail_status = $request->cloud_cron ? $request->cloud_cron : 0;
Use nullable collapsing

2023-06-26 10:28 UTC, RafficMohammed submitted a review, later dismissed

2023-06-29 08:11 UTC, sandesh556 approved these changes

2023-07-06 05:50 UTC, SarfrazS requested changes
Last commits
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/09ee6048-29b1-427c-883c-602c86bedee2)
Migration ran
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/313d31f7-af9b-46cc-b5cc-fba3339b6b3e)

If tenats unable to create then how to check delete functionality.

Trial cloud instance not able to create getting below error.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/678a5355-c302-4bd4-9bdd-38f3f92ef3f2)
From order deploy cloud instance not able to create getting below error
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/70d241c4-65a1-49bd-b1c7-62444cd31243)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/156cffb6-c330-4063-ab96-0284f44f21f2)

2023-07-11 08:12 UTC, SarfrazS submitted a review, later dismissed
pointed issues are fixed now working fine.

2023-07-11 08:49 UTC, sandesh556 approved these changes

2023-07-11 09:03 UTC, closed without merging