UI Changes
ladybirdweb/agora-invoicing-community pull request #2299
Opened 2023-06-13 10:05 UTC by sowmiyasubramaniyan

2023-06-19 04:30 UTC, sandesh556 requested changes

2023-06-19 04:30 UTC, sandesh556 commented on app/Http/Controllers/Auth/LoginController.php
> +        // dd('vbn');
Remove all the commented dd

2023-06-19 04:30 UTC, sandesh556 commented on app/Http/Controllers/Common/BaseSettingsController.php
> +        if ($status == 1) {
you just use $status

2023-06-28 08:01 UTC, sandesh556 submitted a review, later dismissed

2023-07-04 07:02 UTC, SarfrazS requested changes
- [ ] User is requesting a demo, Country code showing twice on the company email.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/2da2d748-0274-4d0c-9903-51c787f2a93b)

- [ ]After the demo request is sent, but In the Helpdesk ticket gets created with the billing system email. How to support team will coordinate with them. The user is not registered in the helpdesk so they can't add in Cc also. The second thing is when the agent replies again will go to the billing system mail.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/7a895176-3012-4e34-a500-1ffea99760f8)

- [ ] For more user friendly please add here Book Demo for Helpdesk/ServiceDesk.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/0041bad4-f71a-4286-8bdb-45ce02a93ffd)

- [ ] No alert message showing when we are passing an invalid email format.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/1a8a8b26-9dd2-49b4-b3c9-e554d738c811)

- [ ] Query:- After logged in why we are not allowing requests for a demo?

2023-07-18 06:48 UTC, bhanu2217 commented
**Changes suggested for demo page:**

- Give option in the admin panel to enable/disable this page
- Top Menu bar design is breaking, compare it with original/live billing page
- Show me another option for the buttons Signup for free, request a demo. Move Signup for free to right
- Country code on first time opening should be based on users IP address.

2023-07-19 11:44 UTC, RafficMohammed commented on app/Http/Controllers/Auth/RegisterController.php
> +                // 'country' => $request->input('country'),
remove this line

2023-07-19 11:48 UTC, RafficMohammed commented on app/Http/Controllers/Common/BaseSettingsController.php
> +        StatusSetting::where('id', 1)->update(['v3recaptcha_status' => $status]);
Don't include id directly

2023-07-22 06:27 UTC, bhanu2217 commented
The email that goes out in that email Reply to email address should be of the customer who filled the form.

2023-07-27 02:48 UTC, bhanu2217 commented
@sowmiyasubramaniyan mentioned this form is using Faveo's create ticket API.

Agora Invoicing is designed like a product. How will this page work for other's who are using this software and not using Faveo Helpdesk?
Ideally we should have used simple mail functionality with reply to

Awaiting your response.

2023-08-01 05:07 UTC, bhanu2217 commented
**Feedback:**

**Setting changes:**

- Keep only page enable/disable button
- To email will be system email
- Reply to will be customer filled email

2023-08-07 07:14 UTC, SarfrazS requested changes
Last commit
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/49b13cdf-e5b9-494d-a761-be745710f6fc)
I ran php artisan migrate
Unable to test getting below error. Please fix and let me know then i will continue testing.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/72eae560-8a19-40d2-9558-5099a12b7d19)

2023-08-07 12:47 UTC, sowmiyasubramaniyan commented
New PR : https://github.com/ladybirdweb/agora-invoicing-community/pull/2447

2023-08-07 12:47 UTC, closed without merging