Tenat Table Refinement
ladybirdweb/agora-invoicing-community pull request #2327
Opened 2023-06-26 06:33 UTC by sowmiyasubramaniyan

2023-06-26 10:30 UTC, RafficMohammed approved these changes

2023-06-28 07:50 UTC, sandesh556 submitted a review, later dismissed

2023-06-30 11:20 UTC, SarfrazS requested changes
- [ ] Issue1: With fresh install Tenants data table not opening it's keep on loading.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/de513c4a-e3c8-4bcb-a8f5-1b851e7883fa)

2023-06-30 11:31 UTC, sowmiyasubramaniyan commented
Fixed

2023-06-30 11:40 UTC, SarfrazS approved these changes
Before Fix:-
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/9f5f0054-53bf-4c92-bcfe-659c573882ac)
After Fix:-
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/db90f910-7105-4847-b969-f5b7d8eeb04e)

2023-07-03 15:17 UTC, merged