Php Mail
ladybirdweb/agora-invoicing-community pull request #2372
Opened 2023-07-14 13:29 UTC by sowmiyasubramaniyan

2023-07-18 06:53 UTC, bhanu2217 commented
@sowmiyasubramaniyan Please connect with me and show me demo of this page and take my feedback

2023-07-19 11:38 UTC, RafficMohammed commented on app/Console/Kernel.php
>              $clouds = cloudemailsend::all();
use cursor() instead of all()

2023-07-19 11:40 UTC, RafficMohammed commented on app/Http/Controllers/Auth/BaseAuthController.php
> +
🚩

2023-07-19 11:41 UTC, RafficMohammed commented on app/Http/Controllers/Auth/ForgotPasswordController.php
> +            $user = new \App\User();
🚩

2023-07-19 11:42 UTC, RafficMohammed requested changes
Discuss with me

2023-07-24 07:15 UTC, sandesh556 commented
change the label after emails are handled through jobs

2023-07-27 04:31 UTC, sandesh556 commented
rebase and convert it for cloud also

2023-07-27 11:59 UTC, sowmiyasubramaniyan commented
> rebase and convert it for cloud also

Done

2023-07-28 05:24 UTC, sandesh556 requested changes

2023-07-28 05:24 UTC, sandesh556 commented on app/Http/Controllers/Tenancy/TenantController.php
> +        $setting = Setting::find(1);
don't change the variable name

2023-07-28 05:24 UTC, sandesh556 commented on app/Http/Controllers/Tenancy/TenantController.php
> +                    $mail->SendEmail($setting->email, $user, $userData, 'New instance created');
Also how will the template be sent?

2023-07-28 05:24 UTC, sandesh556 commented
i see that variable name is changed in few places

2023-08-01 05:15 UTC, bhanu2217 commented
Looks good. Lets proceed.

2023-08-01 07:46 UTC, sandesh556 approved these changes

2023-08-07 06:18 UTC, RafficMohammed submitted a review, later dismissed

2023-08-07 10:10 UTC, SarfrazS requested changes
I Configured php mail and then server team has configured horizon. After that i purchase products. Mail  receiving but pending job, complete job and  failed job are not keep on loading....
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/35ee0df9-ff2b-4fd1-b654-c1a2952a8f15)

2023-08-09 12:47 UTC, SarfrazS requested changes
- [ ] Issue1:- With redis Registration conformation and verification mail are not sending.
- [ ] Issue2:- With redis invoice generation mail not sending.
- [ ] Issue3:- With redis Remider and expiry mail not sending.
- [ ] Issue4:-  Horizon not working.
Query:- Driver i selected php mail now i entered gmail id its accepting is it correct.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/90989f9a-7f20-4258-9b4b-10cd070379ee)

2023-08-12 16:52 UTC, sowmiyasubramaniyan commented
@SarfrazS mails are going with Redis please check again. Except horizon mentioned issues are fixed.

2023-08-18 17:49 UTC, SarfrazS approved these changes
Perpetual products notification checked, all are sending with redis queue from PHP mail driver.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/561386bf-de2d-4cdc-8657-9747fde61c16)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/6b30ffa3-3dae-4e21-98b5-2354ef97a55d)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/ac1d8485-c652-48f6-a9c8-727d2a903c60)

Note:- Cloud notification and horizon will check on a separate instance.

2023-08-21 08:01 UTC, SarfrazS commented
@sowmiyasubramaniyan Please resolve conflicts and let us know.

2023-08-25 04:35 UTC, SarfrazS commented
@sowmiyasubramaniyan Please resolve the conflicts and let me know.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/d1c8977c-70be-404b-9956-1d8f1d4ad230)

2023-08-25 06:38 UTC, Sabaric12 commented
While Making the Payment we are getting this below error
![Screenshot from 2023-08-25 12-00-52](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/faee5a06-4740-451c-8904-76bbd8a1ce91)

2023-08-25 13:00 UTC, Sabaric12 commented
Tested this pr with the Server instance 
Now all the mentioned issues are working fine now
![Screenshot from 2023-08-25 18-28-06](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/d79984de-2b21-4674-8bf8-1045987dd53e)
![Screenshot from 2023-08-25 18-28-24](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/b8e8c59f-676f-417f-a8ed-b21be3deb47d)

2023-08-25 13:00 UTC, Sabaric12 submitted a review, later dismissed

2023-08-25 13:03 UTC, Dhayanan commented
Tested this PR on existing DB on server:-
Mentioned issues are working fine. now  we are able recevie the mail for all the template
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/109129703/2ecc187f-2a82-4b6e-9f7b-d78314488310)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/109129703/8e5a461b-a67e-40c6-98d8-542cbcbbeb1a)

2023-08-25 13:03 UTC, Dhayanan submitted a review, later dismissed

2023-08-28 03:38 UTC, sandesh556 commented
@sowmiyasubramaniyan get a free cloud environment from thiru then we'll do this

2023-08-29 14:36 UTC, Sabaric12 commented
Tested this pr with the Cloud 
![Screenshot from 2023-08-29 20-01-57](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/559e69a5-861f-4b6d-8af8-c7713d204143)
![Screenshot from 2023-08-29 20-04-22](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/5768738b-fb83-4ff2-adeb-dab3664ecb90)
Server instance
Now all the mentioned issues are working fine now
Note:
The Horizon alone not fixed developer told it will be fixed on next release and in the mail template changes the name that also developer said she will fix in next release

2023-08-29 14:37 UTC, Sabaric12 approved these changes

2023-08-29 17:09 UTC, SarfrazS commented
@Sabaric12 Have you tested with php mail driver?

2023-08-30 07:02 UTC, SarfrazS commented
@sowmiyasubramaniyan Except Logo all issues are fixed. Once the logo issue fixes please let me know will retest it.

2023-08-30 09:39 UTC, SarfrazS submitted a review, later dismissed
Now company logo showing on mail  
 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/60c986ca-335a-4ece-aae6-fb59a2fe55c2)

2023-08-30 11:47 UTC, merged