Package updated for error logs
ladybirdweb/agora-invoicing-community pull request #2407
Opened 2023-07-24 09:04 UTC by sowmiyasubramaniyan

2023-07-25 06:22 UTC, sandesh556 approved these changes

2023-07-26 08:05 UTC, ajaz-ul-haq commented on app/Http/Controllers/Common/PhpMailController.php
> +        dispatchNow($job);
unnecessary variable

2023-07-26 08:05 UTC, ajaz-ul-haq commented on app/Http/Controllers/Common/PhpMailController.php
> +                $product = Product::find($data->product_id);
Use model instead of DB statements

2023-07-26 08:05 UTC, ajaz-ul-haq commented on app/Http/Controllers/Common/PhpMailController.php
> +                $id = \DB::table('installation_details')->where('order_id', $order->id)->value('installation_path');
Model

2023-07-26 08:07 UTC, ajaz-ul-haq commented on app/Http/Controllers/Common/PhpMailController.php
> +                        $settings = $settings->where('id', 1)->first();
$settings = ( new \App\Model\Common\Setting())->first(); , check this

2023-07-26 08:25 UTC, ajaz-ul-haq approved these changes

2023-07-31 05:46 UTC, SarfrazS requested changes
Issue:- log Delete functionality not working from data table and from view page also.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/224b11d3-ae0a-491b-8ea7-1fc4b7f03f06)

Query 1:- In which basis we are showing percentage and under line in log view page.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5ee29003-a431-418b-8335-eaa67ca9985b)
Query 2:- Why it's not clickable?

2023-07-31 12:35 UTC, bhanu2217 commented
Saw the demo, looks good. Approving

2023-08-10 08:08 UTC, SarfrazS requested changes
Still we are not able to delete old logs from data table but from search we can delete. See in below gif
![Addmedia](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/9a6de25f-5723-457c-b55b-da75cd732fdc)

2023-08-11 04:23 UTC, SarfrazS commented
Because of a conflict, I'm getting the below error please resolve the conflict.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/53f1a38d-e449-423d-ac4a-9a3a6fdd78e9)

2023-08-11 04:42 UTC, sowmiyasubramaniyan commented
> Because of a conflict, I'm getting the below error please resolve the conflict. ![image](https://user-images.githubusercontent.com/18435376/259922398-53f1a38d-e449-423d-ac4a-9a3a6fdd78e9.png)

I have resolved the conflicts, this issue is because user information is deleted so it's conflicting with the invoice and order details in the dashboard, please check with any other database.

2023-08-11 06:06 UTC, SarfrazS approved these changes
Pointed issues are fixed now working fine.

2023-08-16 08:18 UTC, Sabaric12 approved these changes
Tested this pr with the existing installation
The issue is working fine now we can be able to delete the logs from the data table and we can able to view that also

2023-08-18 08:24 UTC, merged