Datetime
ladybirdweb/agora-invoicing-community pull request #2486
Opened 2023-08-21 16:44 UTC by Gurmeenkour99

#2245 #2360 #2438 fixes

2023-08-22 04:50 UTC, sowmiyasubramaniyan requested changes

2023-08-22 04:50 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Front/BaseClientController.php
> +        dd('jhgfcx');
remove dd

2023-08-22 06:46 UTC, Gurmeenkour99 commented on app/Http/Controllers/Front/BaseClientController.php
> +        dd('jhgfcx');
pushed

2023-08-24 12:30 UTC, sowmiyasubramaniyan submitted a review, later dismissed

2023-08-25 05:31 UTC, sandesh556 approved these changes

2023-08-25 09:46 UTC, SarfrazS commented
@Gurmeenkour99 Please resolve conflicts and let me know.

2023-08-26 05:42 UTC, Gurmeenkour99 commented
Conflicts has been resolved

2023-08-28 07:36 UTC, DhanyaChengappa commented
@Sabaric12 Update these details:

**First Round Test summary**
Total time in days:

Total issues:
Minor -
Major -
critical -

**Second Round Test summary**
Total time in days:

Total issues:
Minor -
Major -
critical -

2023-08-28 11:40 UTC, Sabaric12 commented
Tested this pr with the existing installation on server instance 
The Mentioned Issues are working fine now 
With The Admin Login with the Pacific/Midway time zone now I purchased the product the time is coming according to the Pacific/Midway time zone only
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/4abb2b2c-bfa3-40fd-a6c7-33284e1b83ca)
I Tested the user with the Australia/Melbourne Timezone and Asia/Kolkatta Timezone
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/c5f3b271-95ad-46d3-a1d2-2210049bde18)
First Round Test summary
Total time in days:5 Hours
Total issues:0
Minor -
Major -
critical -

2023-08-28 11:41 UTC, Sabaric12 approved these changes

2023-08-28 12:08 UTC, SarfrazS approved these changes
Last commits
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5a2d6733-a823-4b32-bbf9-57513ee0b3bd)
Re-tested on server instance in below places with different time zone. Working fine.

1. Invoice popup Page.
2. Order data table page
3. Invoice data table page.
4. Order view page
5. Invoice view page.

Second Round Test Summary
Total time in days:1 Hours
Total issues:0
Minor -
Major -
critical -

Note:- Based on the user's time zone, time is showing for him.

2023-08-28 13:42 UTC, merged