Deployment flow break, Admin can create cloud for anybody and non authenticated users will see Free trial option
ladybirdweb/agora-invoicing-community pull request #2611
Opened 2023-09-20 12:15 UTC by sandesh556

2023-09-26 08:03 UTC, DhanyaChengappa commented
**Demo feedback:**

- [ ] Domain name can be below product name or any other suitable place within the item borders

<img width="695" alt="Screenshot 2023-09-26 at 1 32 44 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/1592705/7ff7bfc0-34de-4a18-847a-ad5192233e65">

2023-09-26 09:36 UTC, sandesh556 commented
![Screen Shot 2023-09-26 at 2 42 53 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/d49bfd89-971f-4a25-b735-cad23334d4c9)

2023-10-04 06:08 UTC, sandesh556 commented
- Verify Button is removed or not I mean deploy from everywhere.

2023-10-04 12:24 UTC, RafficMohammed commented on app/Http/Controllers/Tenancy/TenantController.php
> +            dd($company);
Remove the dd

2023-10-04 12:30 UTC, RafficMohammed requested changes

2023-10-04 12:30 UTC, RafficMohammed commented on bootstrap/cache/services.php
>          33 => 'GrahamCampbell\\Markdown\\MarkdownServiceProvider',
🚩. Remove this cache file bro

2023-10-04 12:30 UTC, RafficMohammed commented on resources/views/themes/default1/front/postPaymentTemplate.blade.php
> +      <a href= product/download/{{$order->product}}/{{$invoice->number}} " class="btn btn-sm btn-primary btn-xs" style="margin-bottom:15px;"><i class="fa fa-download" style="color:white;"> </i>&nbsp;
href ="{{ url("product/download/$order->product/$invoice->number") }}"

2023-10-11 08:26 UTC, SarfrazS reviewed
Below Features we are added in this pr:-

1. Authenticated user also can see cloud free trial button.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/3eff318d-9fe1-405c-8df3-06b5f41a27ea)
2. When authenticated user click on free trial below alert message display.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/48520ee7-4b5b-4064-9438-685ffe663396)
3. Unauthenticated users click on cloud free trial and then click on login, after login cloud creation popup will display.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5b79e0a0-b6e9-4eae-a56e-7486bf8323d6)

5. Unauthenticated users click on cloud free trial and then click on register and then click on login after login cloud creation popup will display.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/2aff2ff8-05a6-4523-ba8f-2d6772748f9a)
6. Login and click on cloud free trial that time domain name will filled with your company name.
7. Admin can deploy cloud instance. Create invoice and execute invoice. after that deploy will done for the user. 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/6f74f9f6-d58f-4e8a-aa8c-523822d35f63)
8. User will receive two mails one for purchase and another for cloud creation.

2023-10-11 10:08 UTC, SarfrazS approved these changes
Above all features are working fine.
**First-Round Test Summary:**
**Total time in days/hours: 5 hours**
**Total issues: 2**
Minor: 2
Major: 0 
Critical: 0

2023-10-11 10:42 UTC, merged