Duplication of orders, if there are multiple installation paths for the same order
ladybirdweb/agora-invoicing-community pull request #2675
Opened 2023-10-06 05:48 UTC by sowmiyasubramaniyan

2023-10-09 04:45 UTC, sandesh556 submitted a review, later dismissed

2023-10-12 10:30 UTC, RafficMohammed submitted a review, later dismissed

2023-10-13 08:10 UTC, sandesh556 requested changes

2023-10-13 08:10 UTC, sandesh556 commented on app/Http/Controllers/Order/OrderController.php
> +        $count = count($query->get()->toArray());
why is there 2 counts

2023-10-13 09:33 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Order/OrderController.php
> +        $count = count($query->get()->toArray());
I have removed

2023-10-13 10:39 UTC, sandesh556 approved these changes

2023-10-13 11:08 UTC, SarfrazS approved these changes
Pointed issue is fixed it's was happening only for test product not live product.
First Round Testing Summary:-
Total issue- 0

2023-10-13 11:29 UTC, merged