Reply to & Email templates added for contact us and demo request
ladybirdweb/agora-invoicing-community pull request #2741
Opened 2023-10-19 10:18 UTC by sowmiyasubramaniyan

2023-10-23 12:13 UTC, sandesh556 approved these changes

2023-10-27 04:57 UTC, RafficMohammed approved these changes

2023-11-14 10:29 UTC, SarfrazS requested changes
Last commits:-
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/3e2ddc45-400c-4616-8737-c9268f848992)
I ran migration.
- [ ] While sending message from contact us page getting below error.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/4addd2b0-4bc6-47a2-88c7-74bfe3499628)
- [ ] While sending a request for demo from Request a demo page getting below error.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/e7f24fd8-46f8-4f73-9263-cb8b341e8205)
- [ ] On template contact us and demo drop down value not showing.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/d9e76a47-294b-4bde-a668-f1be2f412ac1)

2023-12-07 07:29 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the fresh installation in the local 
The mentioned issue is working fine now
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/1fe24c51-dc77-4f52-9d86-82cc30e1c720)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/cccb8f1d-7b14-4ef3-b09d-dfe684c1806e)

2023-12-12 13:02 UTC, ganthimathin approved these changes
Tested this issue in local. Its fixed.

Second round test summary:

Total time in days: 4 hours
Total issue: 0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

2023-12-14 04:30 UTC, merged