License Manager Changes
ladybirdweb/agora-invoicing-community pull request #2742
Opened 2023-10-19 13:09 UTC by Gurmeenkour99

This PR need to be tested with License Manger PR for the integration purpose . In this PR client_role is added in the CURL request.
https://github.com/ladybirdweb/agora-license-manager/issues/178

2023-10-20 06:09 UTC, sowmiyasubramaniyan submitted a review, later dismissed

2023-10-23 05:51 UTC, sandesh556 requested changes

2023-10-23 05:51 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +            license_client_role='admin'&license_support_date=$supportExpiry&license_disable_ip_verification=0&license_limit=1", $token);
why are we adding client role to this API, the end point doesn't even accept it

2023-10-30 06:25 UTC, sandesh556 requested changes

2023-10-30 06:25 UTC, sandesh556 commented on app/Http/Controllers/License/LicenseController.php
> +            $addLicense = $this->postCurl($url.'api/admin/license/add', "api_key_secret=$api_key_secret&product_id=$productId&license_code=$serial_key&license_require_domain=1&license_status=1&licens
if there no change done here, revert these changes

2023-11-14 04:22 UTC, SarfrazS commented
@Gurmeenkour99 What are the modules and functionality needed to test in this PR?

2023-11-14 09:40 UTC, SarfrazS commented
Dependency PR License Manager https://github.com/ladybirdweb/agora-license-manager/pull/177 Migration Not working once working then will start testing this pr.

2023-12-15 08:15 UTC, SarfrazS approved these changes
Working fine.

2023-12-15 08:57 UTC, merged