Sorting Invoices and Address fixes
ladybirdweb/agora-invoicing-community pull request #2765
Opened 2023-11-01 06:58 UTC by Gurmeenkour99

#2740 #2750 fixes

Adjusted address spacing and fixed the sorting based on date field.

2023-11-02 03:10 UTC, sandesh556 approved these changes

2023-11-02 04:54 UTC, sowmiyasubramaniyan requested changes

2023-11-02 04:54 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Order/InvoiceController.php
> +        $query->orderBy('date', 'desc');
I don't think the sorting arrows will work after adding the orderBy

2023-11-03 04:24 UTC, sowmiyasubramaniyan requested changes

2023-11-03 04:24 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Order/InvoiceController.php
> +        $query->orderBy('date', 'desc');
Remove this

2023-11-03 05:32 UTC, sowmiyasubramaniyan approved these changes

2023-11-04 05:35 UTC, sandesh556 requested changes
I need to see test cases also

2023-11-04 05:35 UTC, sandesh556 commented on app/Http/Controllers/Order/InvoiceController.php
> +         ->orderColumn('number', '-invoices.date $1')
Lets discuss this once

2023-11-04 08:34 UTC, Gurmeenkour99 commented on app/Http/Controllers/Order/InvoiceController.php
> +         ->orderColumn('number', '-invoices.date $1')
Sure

2023-11-06 06:12 UTC, Gurmeenkour99 commented
@sandesh556 As per our discussion, I will begin reviewing the invoice orders in all the other sections.

2023-11-07 09:45 UTC, sowmiyasubramaniyan requested changes

2023-11-07 09:45 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/Front/ClientController.php
> +                    ->orderColumn('pais', '-invoices.date ASC')
paid or pais?

2023-11-09 04:52 UTC, sowmiyasubramaniyan approved these changes

2023-11-10 10:42 UTC, sandesh556 submitted a review, later dismissed

2023-12-06 08:35 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the fresh installation 
The mentioned issue is working fine now 
Before Fix:
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/ebd91465-90ed-4118-96f6-61ed0f6f6f3f)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/182010a6-f2fd-47c2-ab6c-791708e3a293)
After Fix:
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/d066503a-f9c5-45ed-a571-c80a6888874f)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/eb62f313-d8a7-4d45-b027-9774b441fccd)
Total time in days: 1 day
Total issues: 0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

2023-12-06 08:36 UTC, Sabaric12 submitted a review, later dismissed

2023-12-13 09:38 UTC, ganthimathin requested changes
I tested the sorting and Address space issues in existing DB.

Sorting issue fixed in Admin panel>Inovices table only.

In All users > select a user > in their invoices table - sorting is not working.
In Client panle > Inovices - sorting is not working.

Address space:

An extra comma , is showing in address field. - not fixed

In the attached image after address 4 (.) full stop is showing after that comma is added unncessarily.

[Invoice sorting not working in client panel.webm](https://github.com/ladybirdweb/agora-invoicing-community/assets/131641568/4031ef21-db3f-446d-b21c-19e9e894808d)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/131641568/70201438-e44d-4901-90ce-f10348b4578e)

2023-12-16 05:21 UTC, ganthimathin approved these changes
Verified the mentioned issues in local-exiting DB. Issues are fixed.

Round 2 test summary:

Total time in days: 2 hours
Total issues: 2
Minor - 2
Major - 0
Critical - 0
No of times PR was sent for Functionality correction: 1
PR breaks existing functionality: No

![Address comma issue fixed](https://github.com/ladybirdweb/agora-invoicing-community/assets/131641568/fe59f931-dbe1-4a81-b5de-1919a3ef8030)

2023-12-18 04:55 UTC, merged