Cloud clean up
ladybirdweb/agora-invoicing-community pull request #2772
Opened 2023-11-10 09:26 UTC by sandesh556

2023-11-23 07:25 UTC, sowmiyasubramaniyan submitted a review, later dismissed

2023-12-07 05:08 UTC, bhanu2217 commented
**Few things to consider:**

- Lets remove anything hardcoded
- No where it should say Faveo
- No assumptions, as many options to choose and configure
- Anybody should be able to use Agora Invoicing and integrate there Saas model into it. Clear documentation is also a key here

2023-12-26 12:48 UTC, SarfrazS requested changes
Issue:- Without login start free trial button not clickable.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/465be863-3afc-4b72-a96b-40c0afab5e64)
Issue:- With login also not able to create trial instance.
![Uploading image.png…]()

2023-12-28 06:20 UTC, sowmiyasubramaniyan submitted a review, later dismissed

2023-12-29 06:51 UTC, SarfrazS approved these changes
All Pointed issues are fixed working fine.

Test Summary
No of days in testing:- 2 and half days
Total issues:- 6
Minor issue:- 2
Major issues:- 2
Critical issues:- 2

2023-12-29 06:56 UTC, merged