License Code and Knowledge base URL
ladybirdweb/agora-invoicing-community pull request #2781
Opened 2023-11-13 05:56 UTC by Gurmeenkour99

Corrected the redirection for knowledge base and get license Code URL in the purchase email template and also added the option in system settings to add the knowledge base URL.
#2658 #2751 #2752

2023-11-23 07:23 UTC, sowmiyasubramaniyan submitted a review, later dismissed

2023-12-07 04:21 UTC, sandesh556 approved these changes

2023-12-08 09:24 UTC, Sabaric12 commented
Tested this Prrwith the existing instance
Issue 1:
In the Store, the Products are not showing properly it is overlapping with each other
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/4d7c3890-0f62-4d61-919e-c2abcd8db343)
Issue 2:
After purchasing the product email is not receiving
Total time in days: 5 hours
Total issues: 2
Minor - 0 
Major - 0 
Critical - 2
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

2023-12-11 08:32 UTC, Gurmeenkour99 commented
@Sabaric12 The overlapping issue you have mentioned is an existing issue and this has been resolved now in client panel theme PR and the email sending issue is due to database setup or some invalid details in records. 
i also tried this and i'm receiving the mail .

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/47263a43-a5ea-4b99-9616-dc203658c660)

2023-12-12 05:48 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the existing instance in the server
The mentioned issues are working fine now
Before Fix:
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/404ad957-d073-45d6-9b2a-262da2a90ef9)
After Fix:
![Screenshot from 2023-12-12 11-13-10](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/93b96ade-64ea-45a5-9782-28bfca3f6ff4)
Total time in days: 1 day
Total issues: 0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No
Note:
The overlap issue in the Client panel purchase product is fixed in the Client panel theme PR 
https://github.com/ladybirdweb/agora-invoicing-community/pull/2787
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/faf4bb86-0ccc-4871-b645-b5e50e7ca5cc)

2023-12-12 05:48 UTC, Sabaric12 submitted a review, later dismissed

2023-12-14 07:20 UTC, ganthimathin requested changes
Tested the issues with existing DB.

License code page is showing now. But Knowledge base URL- is not getting launched once clicked from purchase confirmation mail.

2023-12-15 10:50 UTC, Gurmeenkour99 commented
@ganthimathin please try to run seeder command php artisan db:seed --class=Database\\Seeders\\v3_0_5\\DatabaseSeeder

2023-12-15 14:24 UTC, ganthimathin submitted a review, later dismissed
Verified this issue in server instance. There its working fine.
Both licencode and knowledge base URL is getting opened.

2023-12-15 14:26 UTC, ganthimathin commented
Total time in days: 5 hours
Total issues: 0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

2023-12-15 14:27 UTC, ganthimathin commented
> @ganthimathin please try to run seeder command php artisan db:seed --class=Database\Seeders\v3_0_5\DatabaseSeeder

I ran the command. But issue with my local host only. Now in server instance its working fine..

2023-12-18 04:57 UTC, sandesh556 requested changes

2023-12-18 04:57 UTC, sandesh556 commented on database/seeders/v3_0_5/DatabaseSeeder.php
> +    Template::where('id',4)->update(['name' => 'Purchase confirmation', 'type' => 7, 'url' => 'null', 'data' => '<table style="background: #f2f2f2; width: 700px;" border="0" cellspacing="0" cellpaddi
How do you know the id is going to be 4?

2023-12-18 12:11 UTC, merged