Undefined variable $order_id
ladybirdweb/agora-invoicing-community pull request #2796
Opened 2023-12-01 12:24 UTC by sowmiyasubramaniyan

2023-12-07 04:26 UTC, sandesh556 requested changes
why is this moved, it makes no sense. if you are getting no order_id just use optional

2023-12-08 02:46 UTC, sandesh556 approved these changes

2023-12-12 05:17 UTC, RafficMohammed requested changes

2023-12-12 05:17 UTC, RafficMohammed commented on app/Http/Controllers/Order/RenewController.php
> +            $sub = Subscription::find($id);
$order_id = Subscription::whereid($id)->value('order_id');

2023-12-12 12:17 UTC, RafficMohammed approved these changes

2023-12-14 06:23 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the server instance
The mentioned issue is working fine now if we click on renew fill in the mandatory fields and save after that the success message comes
Before Fix:
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/7b410869-1c51-4228-9613-07feb16ceb7b)
After Fix:
![Screenshot from 2023-12-14 11-48-46](https://github.com/ladybirdweb/agora-invoicing-community/assets/118339159/e7cafdcb-bfc0-4894-9668-8d12dfe1583b)
Total time in days: 2 hours
Total issues:0 
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality:No

2023-12-14 06:23 UTC, Sabaric12 approved these changes

2023-12-14 10:18 UTC, ganthimathin approved these changes
Tested this issue with existing DB. Issue was fixed.

2023-12-14 10:18 UTC, ganthimathin commented
Second round test summary:

Total time in days: 1 hour
Total issues:0
Minor - 0
Major - 0
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality:No

2023-12-15 03:55 UTC, merged