Searching
ladybirdweb/agora-invoicing-community pull request #2825
Opened 2023-12-26 07:26 UTC by Gurmeenkour99

Fixes #2725 

1.Fix Searching issue in client panel>>my_orders>>download>>product_list and Admin Panel>>users>>orders_list
2.Fix the order of versions in client panel>>my_orders>>download>>product_list .Latest versions are at the top .

2023-12-27 04:21 UTC, sowmiyasubramaniyan requested changes

2023-12-27 04:21 UTC, sowmiyasubramaniyan commented on app/Http/Controllers/User/AdminOrderInvoiceController.php
> +                                });
what about version and status search?

2023-12-28 06:45 UTC, Gurmeenkour99 commented on app/Http/Controllers/User/AdminOrderInvoiceController.php
> +                                });
done

2023-12-28 07:16 UTC, sowmiyasubramaniyan approved these changes

2023-12-28 10:01 UTC, sandesh556 approved these changes

2023-12-29 06:55 UTC, Sabaric12 commented
Round 1: Testing Summary
Tested this PR with the existing instance in the local
Now the mentioned issues are working fine we can able to search for the product with the title and the description in the client panel my order was downloaded in the product list and in the admin panel users' order details with the order no product and status able to  search
Total time in days: 2 hours
Total issues: 0
Minor - 0 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:0
PR breaks existing functionality: No

2023-12-29 06:56 UTC, Sabaric12 approved these changes

2023-12-29 10:15 UTC, SarfrazS approved these changes
Pointed issues are fixed now searching properly.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/87dc72c2-6840-4009-8339-8f240e21ca6b)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/274d7a9d-7dcc-4a39-b3c7-527cda626a7e)

2023-12-29 10:20 UTC, merged