Dashboard widgets filter issue
ladybirdweb/agora-invoicing-community pull request #2894
Opened 2024-02-06 05:38 UTC by sowmiyasubramaniyan

2024-02-07 11:14 UTC, sandesh556 approved these changes

2024-02-12 04:41 UTC, RafficMohammed requested changes
Write test cases for this scenario. If we ignore test cases on Billing, Billing will never reach stablity.

2024-02-12 04:41 UTC, RafficMohammed commented on app/Http/Controllers/Order/OrderSearchController.php
> +        // dd($allInstallation,$join);
remove this line

2024-02-12 12:05 UTC, RafficMohammed submitted a review, later dismissed

2024-02-13 12:36 UTC, AmanpreetLWS requested changes
First round testing summary:
I tested this PR on existing Database. Found some issues in filters and records shown on pressing view all button . 
Testing time : 6 hours
Total number of issues: 5
Major: 0
Minor: 5
Critical: 0
Is the pr breaking any functionalities? : NO
Number of times went for functionality correction: 1
Issues I found : https://docs.google.com/spreadsheets/d/1ntUnc3OIRd71Q_VilQ9lWtU1hZ1ICoFmafBPcXp8FVU/edit?usp=sharing

Note : 
Found issues not related to pr as well will discuss with team and create separate issues if not existing .

2024-02-19 11:30 UTC, AmanpreetLWS commented
First round testing summary:
I tested this PR on existing Database. Above Mentioned Issues where fixed.
Testing time : 2 hours
Total number of issues: 0
Major: 0
Minor: 0
Critical: 0
Is the pr breaking any functionalities? : NO
Number of times went for functionality correction: 1
Issues I found : https://docs.google.com/spreadsheets/d/1ntUnc3OIRd71Q_VilQ9lWtU1hZ1ICoFmafBPcXp8FVU/edit?usp=sharing
Note : 
1. Dashboard now shows same data as in view all (except for module : Products Sold (Last 30 Days) , Total Sold Products)
2. Data for Module (Paid Orders Expiring in Next 30 days) will be shown on the basis of day in month so generally "Feb" has 28 day so the data fill be shown for next 28 day . Data for 29 days expiry not shown .

Screen Shots : 
Products Sold (Last 30 Days) , Total Sold Products :-
![Screenshot from 2024-02-19 16-53-18](https://github.com/ladybirdweb/agora-invoicing-community/assets/153915182/17f11a60-c9eb-4f7c-ab59-ce73b905e6f7)
Data with 29 days of expiry :- 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/153915182/56e02270-f9fb-4665-b274-e50d45b444b3)
![Screenshot from 2024-02-19 16-58-28](https://github.com/ladybirdweb/agora-invoicing-community/assets/153915182/f88f5cf4-066f-48d7-8cea-7f61c376c141)

2024-02-19 11:31 UTC, AmanpreetLWS reviewed
Review Commented Above

2024-02-19 12:11 UTC, AmanpreetLWS approved these changes
All Queries Cleared

2024-02-21 10:07 UTC, SarfrazS approved these changes
Working fine. now whatever we are showing data on dashboard when we click on view all showing same data.
Note:- Product sold by last 30days and Total sold products in this two section when we click on view all show all data there is no filter. For that we have separate issue.

2024-02-22 03:53 UTC, sandesh556 approved these changes

2024-02-22 03:53 UTC, merged