Stripe payment issue fixed
ladybirdweb/agora-invoicing-community pull request #2907
Opened 2024-02-19 13:02 UTC by sowmiyasubramaniyan

2024-02-28 13:11 UTC, RafficMohammed requested changes

2024-02-28 13:11 UTC, RafficMohammed commented on app/Http/Controllers/RazorpayController.php
> +                \Session::forget('items');
\Session::forget([]) => mention all the keys here

2024-03-01 04:51 UTC, RafficMohammed approved these changes

2024-03-01 06:23 UTC, sandesh556 submitted a review, later dismissed

2024-03-11 04:42 UTC, sowmiyasubramaniyan commented
I am putting this on hold for now, as I am fixing and pushing the Razorpay auto-renewal subscription fixes in this same PR. Also, I need to do code cleanup for the payment functions.

2024-03-13 05:06 UTC, SarfrazS requested changes
- [ ] Issue1:- In Auto reminder mail still price showing wrong. Yesterday you told me i fixed it. Please check and let me know.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/73b5a2a2-0599-4705-a8e5-99b9d185a164)

- [ ] Issue2:-Auto payments are failed with 3D card.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/c0eac84d-eed5-4faf-a18a-97b1a8531f30)

- [ ] Issue3:- Unable to test cloud products with 2days plan. in a group showing yearly. but that is also not able to be purchased.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5279cdfc-742a-4548-a336-e3b9dad0527b)

2024-03-22 05:05 UTC, SarfrazS requested changes
- [ ] Issue:- User received start subscription mail but short code, Total amount and make payment button not working.
![Screenshot 2024-03-22 103017](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/154fa6ad-972e-421c-984a-e07292f26c24)

- [ ] When we are editing subscription template getting below error.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/6b78bc33-1115-4a5f-9627-2cd589c80eaf)

2024-03-30 06:56 UTC, SarfrazS requested changes
- [ ] The first time subscription mail was received and I made the manual payment, the second time should auto payment but not happen order expired.

- [ ] I purchased a cloud product with Stripe not receiving subscription mail.
- [ ] I purchased a self-hosted product with Razorpay, but still didn't receive subscription mail.
- [ ] I purchased self-hosted products with USD from Razorpay test card. Auto renewal is enabled but still auto-payment mail is not received.

2024-04-13 08:20 UTC, sandesh556 approved these changes

2024-04-13 10:09 UTC, SarfrazS approved these changes
Tested the below scenarios with Razor pay from Domestic and international cards.
•	Purchases self-hosted products with Razorpay INR currency.
•	Purchases self-hosted products with Razorpay USD currency.
•	Checked purchase confirmation mail received on mail.
•	Checked invoice mail received on mail.
•	Checked order expiry mail received on mail.
•	Checked reminder mail received on mail.
•	Checked manual renewal with INR currency.
•	Check manual renewal with USD currency.
•	Enabled auto-renewal and checked auto-renewal with INR currency.
•	Checked first-time INR currency users subscribe manually after that auto-renewal will be happening.
•	Checked once the INR currency subscription got active then the auto-renewal billing cycle working.
•	Checked after subscription got active next due payment auto payment happening. 
•	Checked subscription mail session expiry, after 24 hours subscription link expired.
•	Checked after the subscription link expired when the user clicked on it showed void. (Message showing from payment gateway)
•	 Enabled auto-renewal and checked auto-renewal with USD currency.
•	Checked for USD currency subscription mail not sending directly autopayment happening.
•	Checked INR currency users can't pay with USD cards.
•	Checked USD currency users can’t pay with INR cards.
•	Checked from which card auto-renewal active from that payment gateway subscription got initialized.
•	Checked country-based plan price auto-renewal.
•	Checked if the country-based plan is not there then picked default price in auto-renewal.
•	Checked failed payment mail received on mail.
•	Purchases Cloud products with Razorpay INR currency.
•	Purchases Cloud products with Razorpay USD currency.
•	Checked Enabled Auto-renewal with INR currency.
•	Checked Enabled Auto-renewal with USD currency.
•	Without agents increase/decrease checked auto-renewal with INR.
•	Without agents increase/decrease checked auto-renewal with INR.
•	First increased Agents and checked auto-renewal with INR.
•	First Increased Agents and checked auto-renewal with USD.
•	First decreased Agents and checked auto-renewal with INR.
•	First decreased Agents and checked auto-renewal with USD.
•	Checked auto-renewal after products upgraded from HDM to SDM with INR.
•	Checked auto-renewal after products upgraded from HDM to SDM with USD.
•	Checked auto-renewal after products were downgraded from HDM to SDM with INR.
•	Checked auto-renewal after products were downgraded from HDM to SDM with USD.

Tested the below scenarios with Stripe from 3DS and non-3DS Cards as well as individual country cards.
•	Purchases self-hosted products with Stripe INR currency.
•	Purchases self-hosted products with Stripe USD currency.
•	Checked purchase confirmation mail received on mail.
•	Checked invoice mail received on mail.
•	Checked order expiry mail received on mail.
•	Checked reminder mail received on mail.
•	Checked manual renewal with INR currency.
•	Check manual renewal with USD currency.
•	Enabled auto-renewal and checked auto-renewal with INR currency.
•	Checked first-time INR currency users subscribe manually after that auto-renewal will be happening.
•	Checked once the INR currency subscription got active then the auto-renewal billing cycle working.
•	Checked after subscription got active next due payment auto payment happening. 
•	Checked subscription mail session expiry, after 24 hours subscription link expired.
•	Checked after the subscription link expired when the user clicked on it showed void. (Message showing from payment gateway)
•	 Enabled auto-renewal and checked auto-renewal with USD currency.
•	Checked for USD currency subscription mail not sending directly autopayment happening.
•	Checked INR currency users can't pay with USD cards.
•	Checked USD currency users can’t pay with INR cards.
•	Checked from which card auto-renewal active from that payment gateway subscription got initialized.
•	Checked country-based plan price auto-renewal.
•	Checked if the country-based plan is not there then picked default price in auto-renewal.
•	Checked failed payment mail received on mail.
•	Purchases Cloud products with Stripe INR currency.
•	Purchases Cloud products with Stripe USD currency.
•	Checked Enabled Auto-renewal with INR currency.
•	Checked Enabled Auto-renewal with USD currency.
•	Without agents increase/decrease checked auto-renewal with INR.
•	Without agents increase/decrease checked auto-renewal with INR.
•	First increased Agents and checked auto-renewal with INR.
•	First Increased Agents and checked auto-renewal with USD.
•	First decreased Agents and checked auto-renewal with INR.
•	First decreased Agents and checked auto-renewal with USD.
•	Checked auto-renewal after products upgraded from HDM to SDM with INR.
•	Checked auto-renewal after products upgraded from HDM to SDM with USD.
•	Checked auto-renewal after products were downgraded from HDM to SDM with INR.
•	Checked auto-renewal after products were downgraded from HDM to SDM with USD.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/36c1db75-848b-41cc-ba75-dff66eec33d6)

2024-04-13 11:06 UTC, merged