Making subtitles bold
ladybirdweb/agora-invoicing-community pull request #2928
Opened 2024-03-14 06:21 UTC by Gurmeenkour99

Fixes #2927 
making the subtitles bold
previous subtitles
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/a7dc2ffa-a295-4573-959b-090544e36550)
updated subtitles
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/b73150de-49f3-498c-ae4e-615be97cdf11)

2024-03-14 08:00 UTC, Gurmeenkour99 commented
@DhanyaChengappa yes both the templates are similar

2024-04-02 04:40 UTC, sowmiyasubramaniyan approved these changes

2024-04-13 13:10 UTC, sandesh556 approved these changes

2024-04-15 07:12 UTC, SarfrazS requested changes
Last commits:-
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/d5cc48e0-3daf-4c0a-916d-70c302a3fb36)

Pointed issue not fixed, before logo was showing correct now logo also showing big. see in the below image.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/8edccb1f-8acc-474f-9942-527b68b7699a)
![Screenshot 2024-04-15 123743](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/84a380e9-2a74-46b2-a426-03d6125e2a6c)

For more reference you can check here:-
https://qa.productdemourl.com/sarfraz/public/
demoadmin
Demopass@123

2024-04-16 06:25 UTC, sowmiyasubramaniyan commented
New PR: #2953

2024-04-22 08:20 UTC, closed without merging