UI 2880
ladybirdweb/agora-invoicing-community pull request #2965
Opened 2024-04-23 11:31 UTC by sowmiyasubramaniyan

2024-04-25 06:18 UTC, sandesh556 submitted a review, later dismissed

2024-04-25 08:14 UTC, RafficMohammed submitted a review, later dismissed

2024-04-26 06:15 UTC, SarfrazS requested changes
- [ ] Add a message for an empty cart, similar to the one in the original theme.
Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/d4edafa9-83fe-4deb-bc93-2ad56004c751)
After Fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/f0792c90-e03b-445b-ab4f-ec06922b0758)
- [ ]  In the invoice email template change the button name to 'View Invoice.
Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/2dcd2ff2-a798-455d-bf63-73feb4108059)
After fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/740e6aff-7c6f-48c6-980c-c26f04a574a5)
 [ ]Need to remove the product from the title, add a license to the code inside the box, and remove the day order email template.
Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/212c7ba5-9a1f-4620-a7ea-166edea46ecd)
After Fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/894f2f50-c1e8-4089-bd49-a2e47a259e51)
- [ ]  Change the font colour and size in the Stripe tax message.
Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/8cf8a727-a3a1-4e8c-9214-939aa72da476)
After fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/a1dbe512-8507-475d-8472-7e344c4731d6)
- [ ] Check the tooltip in the image and remove the version from the checkout page.
Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/c3a56364-600d-43a6-b9a3-3e2a2958fe07)
After fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/5252f87d-3954-4917-9c0a-7b9d6c16500f)
- [ ]Account manager subject is wrong on the templates page.
- Before fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/73bb3100-8a74-4ebe-ba6f-c032c8ab7004)
After fix
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/0f70482c-6ee1-4f40-96d5-b5013d3daeb6)

All Above pointed issues are fixed.
Note:- in cart, when we  mouse over on product it's blinking. is it okay , please comment then i will approve it. see in below gif.
![Addmedia](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/660315dc-e765-4888-93cf-12807339d09d)

2024-04-27 06:24 UTC, sowmiyasubramaniyan commented
> * [ ]  Add a message for an empty cart, similar to the one in the original theme.
>   Before fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325860835-d4edafa9-83fe-4deb-bc93-2ad56004c751.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjA4MzUtZDRlZGFmYTktODNmZS00ZGViLWJjOTMtMmFkNTYwMDRjNzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTNjZjFhOTQyY2U1N2FlZDM5MTkwYTg1ZDM2YjNlMGVmYWViZTI0Y2ZmMjg3OGY1OGUzNTY4Yjg3ZDJmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SAjXijCckIAxmMl5-4FDsrUCz_4bpoxieeMqTCPsj8)
>   After Fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325861122-f0792c90-e03b-445b-ab4f-ec06922b0758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjExMjItZjA3OTJjOTAtZTAzYi00NDViLWFiNGYtZWMwNjkyMmIwNzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MjBkNzhlMWYwZjljYzI4MDUyZDMwNTQ4MzIxNzllZmFjOWEzNjYxZjkxOWUyNWNmOGYwNWIyNjljYzhmNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1gpkBjS08TIIaRn_824ULO9jxp_xK-C0ZnZQvrok4ug)
> * [ ]   In the invoice email template change the button name to 'View Invoice.
>   Before fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325862901-2dcd2ff2-a798-455d-bf63-73feb4108059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjI5MDEtMmRjZDJmZjItYTc5OC00NTVkLWJmNjMtNzNmZWI0MTA4MDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2Mzk5OTNlMDMwZjYxZTJjN2QxMWYzMjg2ZTczYTViODNlNTVkNjMxODkzYzcwYjhjNDMxODk4YmNiZTY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fhJbr_oGZTEIXMp6wa4xdWGTHP-n2jkDARIgcTW5Vg)
>   After fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325863341-740e6aff-7c6f-48c6-980c-c26f04a574a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjMzNDEtNzQwZTZhZmYtN2M2Zi00OGM2LTk4MGMtYzI2ZjA0YTU3NGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYzFjYjYzNDkyMjQyNmQzYmQzMTY2NzNkNTVkYWIwOWJiNjY1ZmI3MGY2ODFlMmYxN2JlMzEzM2Y4NzE4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0uKt55-2FfXujVfwUezXxX5kL5pFr8Wm-glj3Dtvzs)
>   [ ]Need to remove the product from the title, add a license to the code inside the box, and remove the day order email template.
>   Before fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325863551-212c7ba5-9a1f-4620-a7ea-166edea46ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjM1NTEtMjEyYzdiYTUtOWExZi00NjIwLWE3ZWEtMTY2ZWRlYTQ2ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYmJmOGNlZWM3ZjI1MjQ4NGJiN2YwNThhYTVhOTU0NjAyODdiYWZhY2U0NWRkZTEyYTg0NzVmNTE2M2NjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmrNt5vPJWV8O8h4-DdN4S3aRqoaRXR60I0wwBJXlx0)
>   After Fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325863670-894f2f50-c1e8-4089-bd49-a2e47a259e51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjM2NzAtODk0ZjJmNTAtYzFlOC00MDg5LWJkNDktYTJlNDdhMjU5ZTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NWJiN2VjOWRlYWM1YjNiMGIyYTNkZGQzNTM3MmZhMGZkZDYzODllMTcxYWVjZWU0YmI5ZWYyOTJjMzZlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJPsXOj0JQmBrC0XSCP0RurqHdhc_LBmwa2SClw7Cv4)
> * [ ]   Change the font colour and size in the Stripe tax message.
>   Before fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325864127-8cf8a727-a3a1-4e8c-9214-939aa72da476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjQxMjctOGNmOGE3MjctYTNhMS00ZThjLTkyMTQtOTM5YWE3MmRhNDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOGM5MzMyZjVjYzcwMDE5ZWI4ZGIxYmE5NmE4NGRkZmIyYzMzY2IxZjJmMWFlYWMwNzNlOTAwNzFlN2ZkYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKU2iq_LsaZIMfsQ_2_mtEzQpzDgVAqBuKksVJbcEGw)
>   After fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325864281-a1dbe512-8507-475d-8472-7e344c4731d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjQyODEtYTFkYmU1MTItODUwNy00NzVkLTg0NzItN2UzNDRjNDczMWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZDRlZmMyZjhiMjE3NWZlOTc2ZDY2MWYxMjJmNTI2OTAyYjE2YmQ3NzM1ZTEzYzQ4OWMzMmJlYzNiYzUyZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CYdWwXdYTsJmJOXn-5iOiooFJ5ZfjIDibRb2X5wGZKI)
> * [ ]  Check the tooltip in the image and remove the version from the checkout page.
>   Before fix
>   ![image](https://private-user-images.githubusercontent.com/18435376/325865140-c3a56364-600d-43a6-b9a3-3e2a2958fe07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTkzNjMsIm5iZiI6MTcxNDE5OTA2MywicGF0aCI6Ii8xODQzNTM3Ni8zMjU4NjUxNDAtYzNhNTYzNjQtNjAwZC00M2E2LWI5YTMtM2UyYTI5NThmZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MDA1OTg5OGFkYjU4NmIzZjdkYzUwOGZjNmYwZWIyNDU3MTc2NjE0MTI2MTc1ZDM4M2RlZjAyNmQ4ZjYxM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9 [...]

2024-04-27 07:14 UTC, SarfrazS approved these changes
Pointed issue is fixed now working fine.

2024-04-27 07:17 UTC, sandesh556 approved these changes

2024-04-27 07:17 UTC, merged