Debugger issue fixed
ladybirdweb/agora-invoicing-community pull request #3008
Opened 2024-07-02 10:29 UTC by sowmiyasubramaniyan

2024-07-04 04:50 UTC, sandesh556 approved these changes

2024-07-04 07:20 UTC, RafficMohammed approved these changes

2024-07-05 06:50 UTC, indira15v commented
**Round one testing summary**
Tested this PR in local and server 
Testing time :5.5hrs 
Total issue :0
Major : 0
Minor:0
Critical:0
Is the PR breaking any functionalities? : NO
Number of times PR went for functionality correction: 0
Note :
1.The issue was fixed which happened in the development branch while configuring setup 
![Screenshot from 2024-07-05 11-55-32](https://github.com/ladybirdweb/agora-invoicing-community/assets/148183547/c37366d2-513f-417e-bd29-9a4f1cdb640c)
Now it was working fine
![Screenshot from 2024-07-05 12-04-06](https://github.com/ladybirdweb/agora-invoicing-community/assets/148183547/8039baa1-b977-4106-8f0a-08b6d33910f9)
2.Sometimes the inconsistent issue happened because of cache that it got loaded in the same page

2024-07-05 06:51 UTC, indira15v approved these changes

2024-07-07 05:37 UTC, SarfrazS requested changes
**Major issue**:- Installation has successfully done but database table not migrated.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/6c9987fd-436e-4a0c-aa5f-1099fe2a028c)
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/4392ca5d-5178-4aef-a58c-476c56895eb5)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/7e59de10-2c4b-4ed7-8b11-906496a424a7)

2024-07-08 05:55 UTC, SarfrazS approved these changes
Working fine

2024-07-08 12:38 UTC, merged