Billing Installer
ladybirdweb/agora-invoicing-community pull request #3077
Opened 2024-09-25 06:18 UTC by sadhasivam-ladybirdweb

### Issue: #3067

Change the billing installer to be similar to Faveo.

2024-09-26 07:45 UTC, sandesh556 requested changes

2024-09-26 07:45 UTC, sandesh556 commented on routes/web.php
> +//
Lets remove all of this if not needed

2024-09-26 07:45 UTC, sandesh556 commented on app/Http/Controllers/BillingInstaller/BillingDependencyController.php
> +<?php
Make sure all messages are coming from lang

2024-10-01 04:51 UTC, sandesh556 submitted a review, later dismissed

2024-10-01 05:13 UTC, Sakthi002 approved these changes

2024-10-17 04:28 UTC, laksh-22 approved these changes

2024-10-17 12:12 UTC, RafficMohammed approved these changes

2024-10-18 12:17 UTC, Sabaric12 commented
Round 1 Testing Summary:
Tested this pr the issue sheet is mentioned below.
Total time in days: 5 hours
Total issues: 8
Minor - 8 
Major - 0 
Critical - 0
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

2024-10-18 12:32 UTC, indira15v commented
**Round two testing summary**
Tested this PR in local 
Issue sheet
https://docs.google.com/spreadsheets/d/17WwJ7Zfbo5DcOK41CyWH_GE2xkzAGM-H2kB50pxwKJ8/edit?gid=0#gid=0
Total issues: 5
Minor - 1
Major - 4
Critical - 0
No of times PR was sent for Functionality correction:1
PR breaks existing functionality: No

2024-10-24 10:14 UTC, sadhasivam-ladybirdweb commented
CLI installation has also been implemented in this PR, so please review it in both the UI and the CLI.

2024-11-05 07:24 UTC, indira15v commented
Retesting summary
Retested this PR and facing issues mentioned in sheet
https://docs.google.com/spreadsheets/d/17WwJ7Zfbo5DcOK41CyWH_GE2xkzAGM-H2kB50pxwKJ8/edit?gid=0#gid=0

2024-11-05 12:23 UTC, Sabaric12 commented
Round 1 Testing Summary:
Tested this pr the issue sheet is mentioned below.
Total time in days: 2 hours
Total issues: 2
Minor - 1
Major - 1
Critical - 0
No of times PR was sent for Functionality correction:2
PR breaks existing functionality: No
https://docs.google.com/spreadsheets/d/17WwJ7Zfbo5DcOK41CyWH_GE2xkzAGM-H2kB50pxwKJ8/edit?gid=0#gid=0

2024-11-08 11:38 UTC, Sabaric12 commented
Round 1 Testing Summary:
Tested this pr with the fresh installation in the Local and the Server with the Zip File in the GUI and the CLI mentioned issues are working fine now.
Total time in days: 2 hours
Total issues: 11
Minor - 7
Major - 4
Critical - 0
No of times PR was sent for Functionality correction:2
PR breaks existing functionality: No
Note:
**https://docs.google.com/spreadsheets/d/17WwJ7Zfbo5DcOK41CyWH_GE2xkzAGM-H2kB50pxwKJ8/edit?gid=0#gid=0**

2024-11-11 06:51 UTC, indira15v commented
**Round two retesting summary**
Tested this PR  with the fresh installation in the the Server with the Zip File, the GUI and the CLI method also working fine 
No of times PR  sent for Functionality correction:2
PR breaks existing functionality: No
Issue sheet 
https://docs.google.com/spreadsheets/d/17WwJ7Zfbo5DcOK41CyWH_GE2xkzAGM-H2kB50pxwKJ8/edit?gid=0#gid=0

2024-11-11 06:52 UTC, indira15v approved these changes

2024-11-11 08:11 UTC, merged